version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2022
    environment:
      SA_PASSWORD: "ilove392!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - app-network

  webapp:
    build: ./UserManagementApp
    container_name: usermanagementapp
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=UserManagementDB;User Id=sa;Password=ilove392!;TrustServerCertificate=True;
      - JwtSettings__Secret=YourSuperSecretKeyHere
      - JwtSettings__Issuer=YourAppIssuer
      - JwtSettings__Audience=YourAppAudience
      - JwtSettings__ExpiryInMinutes=60
      - ApplicationInsights__InstrumentationKey=YOUR_INSTRUMENTATION_KEY
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - webapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserverdata:
